ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
= Code Examples

[NOTE]
All code in this examples assume that you have bpjs in the `$PATH` environment variable. As an alternative, one can replace the `bpjs` command with `java -jar BPjs-0.9.7.uber.jar` (or any other version later than 0.9.7).

[WARNING]
You must use the uber jar, that contains dependencies used by BPjs (such as Mozilla Rhino).

== Files

link:definitions.js[]::
  Common program definitions, such as events and event sets.

link:pancake-core.js[]::
  The two core b-threads, adding dry and wet mixture doses.

link:viscosity-monitor.js[]::
  A b-thread that keeps track of batter viscosity, and publishes it using an event.

link:viscosity-limiter.js[]::
  A b-thread that limits the viscosity of the batter to have an absolute value less than, or equal to, `VISCOSITY_BOUND`. 

link:viscosity-limiter-faulty.js[]::
  Same as above, but using an off-by-one threshold, dropping the _...or equals to_ clause.

link:add-blueberries.js[]::
  Contains a b-thread that adds blueberries, and other b-threads that prevent this addition when the batter is not ready yet.

link:add-blueberries-verify.js[]::
  Contains a b-thread that verifies that blueberries were indeed added.

link:pancake-core-repeat.js[]::
  The pancake code threads, in an infinite loop. When all the doses are added, a new b-thread requests a `ReleaseBatter` event, and the loop restarts.

link:add-blueberries-repeat.js[]::
  Simplified version of the blueberry adder, requesting that blueberries will be added (no blockers, as we don't need them for the counter examples here).

== Execution Examples

=== Simple Run
5 doses of each mixture, just running.

  $ bpjs definitions.js pancake-core.js

link:logs/simple-run.txt[Sample Log]

=== Run with a limited viscosity.

  $ bpjs definitions.js pancake-core.js viscosity-monitor.js viscosity-limiter.js

link:logs/limited-run.txt[Sample Log]

=== Demonstrate the viscosity-limiter-faulty is indeed faulty

  $ bpjs --verify definitions.js pancake-core.js viscosity-monitor.js viscosity-limiter-faulty.js viscosity-verify.js

link:logs/viscosity-verify-fail.txt[Sample Log]

=== Demonstrate the viscosity-limiter is not faulty

  $ bpjs --verify definitions.js pancake-core.js viscosity-monitor.js viscosity-limiter.js viscosity-verify.js

link:logs/viscosity-verify.txt[Sample Log]

=== Find cases where blueberries are not added

Looking at blueberry addition as a liveness requirement (note the `--liveness` switch) 

  $ bpjs --verify --liveness definitions.js pancake-core.js viscosity-monitor.js viscosity-limiter.js add-blueberries.js add-blueberries-verify.js

link:logs/no-blueberries-live.txt[Sample Log]

Looking at blueberry addition as a deadlock issue. This will fail verification due to a deadlock between the b-thread requesting the addition and the b-thread blocking that addition due to batter thickness. This deadlock is an implementation detail, though; the real specification violated here is the fact that blueberries were not added (hot termination). 

  $ bpjs --verify definitions.js pancake-core.js viscosity-monitor.js viscosity-limiter.js add-blueberries.js

link:logs/no-blueberries-deadlock.txt[Sample Log]

=== Find an infinite run were blueberries are never added

Using `--max-trace-length` to limit the length of the search, as there are short violating cycles. Using `--full-state-storage` to ensure no hash collisions happen.

  $ bpjs  --max-trace-length=100  --full-state-storage --verify  pancake-core-repeat.js  add-blueberries-verify.js add-blueberries-repeat.js

link:logs/hot-bthread-run.txt[Sample Log]